//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public int SenderUserId { get; set; }
        public int ReceiverUserId { get; set; }
        public string Message { get; set; }
        public System.DateTime PostingDateTime { get; set; }
        public bool IsWatched { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
