//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int Id { get; set; }
        public string InnerCode { get; set; }
        public string BaseCode { get; set; }
        public int ProviderId { get; set; }
        public int ManufacturerId { get; set; }
        public string Title { get; set; }
        public int CountInStock { get; set; }
        public decimal PriceOfStockInRubles { get; set; }
        public decimal PricePerUnitInRubles { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
